# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ITb0nwDets_dX71eRsqBtN2lkEg3QWNg
"""

nome = João

nome = 'João'

idade = 26

print(f'O nome é {nome} e a idade é {idade} anos')

idade = 27

print(f'O nome é {nome} e a idade é {idade} anos')



"""Criando a primeira função

"""

def saudacao():
  nome = input('Qual o seu nome? ')
  print(f'Olá {nome}')

saudacao()

nome = 'Bruna'

def saudacao_parametro(nome_pessoa):
  print(f'Olá {nome_pessoa}')

saudacao_parametro(nome)

saudacao_parametro(nome_pessoa)

idade = 12

def valida_perm(idade):
  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

valida_perm(idade)

def valida_perm_sem_parametro():
  idade_text = input('Qual a sua idade? ')
  idade = int(idade_text)
  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

valida_perm_sem_parametro()

def velocidade_f():
  espaco = input('Qual a distância? ')
  espaco = float(espaco)
  tempo = input('Qual o tempo? ')
  tempo = float(tempo)
  velocidade = espaco / tempo
  print(f'Velocidade: {velocidade} m/s')

velocidade_f()

idades = [12, 14, 29, 60]
idades[2]

idades[0:2]

idades[2:]

idades[-1]

idade_lista = [12, 14, 29, 60]
def verifica_idades(idade):
  if idade >= 18:
    print(f'{idade} anos, TEM permissão para dirigir')
  else:
    print(f'{idade} anos, NÂO TEM permissão para dirigir')

for idade in idade_lista:
  verifica_idades(idade)

idade_lista = [12, 14, 29, 60]
def verifica_idades(idade):
  for idade in idade_lista:
    if idade >= 18:
      print(f'{idade} anos, TEM permissão para dirigir')
    else:
      print(f'{idade} anos, NÂO TEM permissão para dirigir')

verifica_idades(idades)

permissoes = []
idades_listas = [12, 20, 78]

def val_perm(idades_listas, permissoes):
  for idade in idades_listas:
    if idade >= 18:
      permissoes.append(True)
    else: 
      permissoes.append(False)

val_perm(idades_listas, permissoes)

permissoes

for permissao in permissoes:
  if permissao == True:
    print('Tem permissão para dirigir')
  else: 
    print('Não tem permissão para dirigir')

lista = ['João', 26, True, '18']

for elemento in lista:
  print(f'O elemento {elemento} é do tipo: ', type(elemento))

from random import randrange

notas = []
randrange(0,11)

notas.append(randrange(0,11))
  notas

notas

from random import randrange

notas_matematica = []
for nota in range(8):
  notas_matematica.append(randrange(0,11))

notas_matematica

len(notas_matematica)

import matplotlib.pyplot as plt
x= list(range(1,9))
y = notas_matematica
plt.plot(x,y,marker='o')
plt.title('Notas de Matemática')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

import matplotlib.pyplot as plt

notas_matematica = ['Matemática',8,7,6,6,7,7,8,10]
notas_portugues = ['Português',9,9,9,8,5,6,8,5]
notas_geografia = ['Geografia',10,10,6,7,7,7,8,7]

notas = [notas_matematica, notas_portugues, notas_geografia]

for nota in notas:
 x = list(range(1, 9))
 y = nota[1:]
 plt.plot(x, y, marker='o')
 plt.xlabel('Provas')
 plt.ylabel('Notas')
 plt.title(nota[0])
 plt.show()

